### ISSUE TITLE
Panic in filter

### ISSUE THREAD

**Issue by beevee** [moira-alert/moira#459]
```
goroutine 91 [running:
github.com/vova616/xxhash.Checksum32Seed(0xc002966050, 0x0, 0x0, 0xc000000000, 0xc0bd7378e6)
    /go/pkg/mod/github.com/vova616/xxhash@v0.0.0-20130313230233-f0a9a8b74d48/xxhash.go:189 +0x19d
github.com/vova616/xxhash.Checksum32(...)
    /go/pkg/mod/github.com/vova616/xxhash@v0.0.0-20130313230233-f0a9a8b74d48/xxhash.go:181
github.com/moira-alert/moira/filter.findPart(0xc002966050, 0x0, 0xc002314e00, 0x1, 0x40, 0xc002314e00, 0x1, 0x40, 0x1)
    /go/src/github.com/moira-alert/moira/filter/pattern_index.go:124 +0xd8
github.com/moira-alert/moira/filter.(*PatternIndex).MatchPatterns(0xc0026f1ce0, 0xc002966050, 0x23, 0xf4e4d0, 0xc002966050, 0xc0025789c0)
    /go/src/github.com/moira-alert/moira/filter/pattern_index.go:107 +0x2f3
github.com/moira-alert/moira/filter.(*PatternStorage).matchPatterns(0xc00010b7c0, 0xc0026f9740, 0xf315c0, 0xc0026f9740, 0x0)
    /go/src/github.com/moira-alert/moira/filter/patterns_storage.go:91 +0x11c
github.com/moira-alert/moira/filter.(*PatternStorage).ProcessIncomingMetric(0xc00010b7c0, 0xc002966050, 0x40, 0x41, 0x0)
    /go/src/github.com/moira-alert/moira/filter/patterns_storage.go:68 +0x1eb
github.com/moira-alert/moira/filter/patterns.(*Matcher).worker(0xc000108cb0, 0xc001a00300, 0xc001a00360, 0x0, 0x0)
    /go/src/github.com/moira-alert/moira/filter/patterns/matcher.go:51 +0x92
github.com/moira-alert/moira/filter/patterns.(*Matcher).Start.func1(0x0, 0x0)
    /go/src/github.com/moira-alert/moira/filter/patterns/matcher.go:35 +0x3c
gopkg.in/tomb%!e(MISSING)v2.(*Tomb).run(0xc000108cc0, 0xc001485660)
    /go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x2b
created by gopkg.in/tomb%!e(MISSING)v2.(*Tomb).Go
    /go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xc7
panic: runtime error: index out of range [0 with length 0
```

**Comment by beevee** [comment]
vova616/xxhash is an old library. And it has warnings about unsafe pointers in README. Maybe we should switch to a maintained library like https://github.com/cespare/xxhash.

**Comment by litleleprikon** [comment]
I think that usage of unsafe pointers is a valuable reason to change library
